version: "3"
services:

  web:
    image: nginx:1.21.4-alpine
    restart: always
    volumes:
      - ./web/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/var/www/app/public
    links:
      - app
    ports:
      - 80:80

  app:
    build: .
    restart: always
    command: bin/rails server -b 0.0.0.0 -p 3000
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://app:password@db/app_development
    volumes:
      - .:/app
    links:
      - db
    ports:
      - 3000:3000

  worker:
    build: .
    restart: always
    command: sidekiq
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://app:password@db/app_development
    volumes:
      - .:/app
    links:
      - db
      - redis

  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data

  redis:
    restart: always
    image: redis:alpine
